version: "3.7"

services:
  pg:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=shopper
      - POSTGRES_PASSWORD=shopper
      - POSTGRES_DB=shopper

    api:
      image: node:20
      container_name: api
      working_dir: /src/shared/http/server
      volumes:
        - .:/src/shared/http/server
      ports:
        - "3333:3333"
      environment:
        DATABASE_URL: postgres://shopper:shopper@pg:5432/shopper
      depends_on:
        - pg
      command: sh -c "npm install && npx prisma migrate dev && npm run dev"
